/**
 * @file Version.h
 * @brief Version information for INA3221.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef INA3221_VERSION_STRING
#define INA3221_VERSION_STRING "1.2.0"
#endif

#ifndef INA3221_BUILD_DATE
#define INA3221_BUILD_DATE __DATE__
#endif

#ifndef INA3221_BUILD_TIME
#define INA3221_BUILD_TIME __TIME__
#endif

#ifndef INA3221_BUILD_TIMESTAMP
#define INA3221_BUILD_TIMESTAMP INA3221_BUILD_DATE " " INA3221_BUILD_TIME
#endif

#ifndef INA3221_GIT_COMMIT
#define INA3221_GIT_COMMIT "unknown"
#endif

#ifndef INA3221_GIT_STATUS
#define INA3221_GIT_STATUS "unknown"
#endif

#ifndef INA3221_VERSION_FULL
#define INA3221_VERSION_FULL INA3221_VERSION_STRING " (" INA3221_GIT_COMMIT ", " INA3221_BUILD_TIMESTAMP ", " INA3221_GIT_STATUS ")"
#endif

namespace INA3221 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 2;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full semantic version string.
static constexpr const char* VERSION = INA3221_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 10200;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 10200;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = INA3221_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = INA3221_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = INA3221_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = INA3221_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = INA3221_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = INA3221_VERSION_FULL;

}  // namespace INA3221
